Posttest 4
nama : Asrina Nur Syahbani
nim  : 2009106131

In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# untuk Data Split
from sklearn.model_selection import train_test_split #testing dan training data
# untuk Data Transforming
from sklearn.preprocessing import StandardScaler #standarisasi
from sklearn.preprocessing import MinMaxScaler #normalisasi
# untuk Data Cleaning
from sklearn.impute import SimpleImputer #subtitusi nilai
# untuk Data Encoding
from sklearn.preprocessing import OrdinalEncoder #encoder
from sklearn.preprocessing import OneHotEncoder #onehot

In [2]:
df = pd.read_csv('fruits.csv')
df.head()

fruit_label fruit_name fruit_subtype   mass  width  height  color_score
0            1      apple  granny_smith  192.0    8.4     7.3         0.55
1            1      apple  granny_smith  180.0    8.0     6.8         0.59
2            1      apple  granny_smith  176.0    7.4     7.2         0.60
3            2   mandarin      mandarin   86.0    6.2     4.7         0.80
4            2   mandarin      mandarin   84.0    6.0     4.6         0.79

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fruit_label    60 non-null     int64  
 1   fruit_name     60 non-null     object 
 2   fruit_subtype  60 non-null     object 
 3   mass           51 non-null     float64
 4   width          60 non-null     float64
 5   height         51 non-null     float64
 6   color_score    60 non-null     float64
dtypes: float64(4), int64(1), object(2)
memory usage: 3.4+ KB


In [4]:
df.isna().sum()

fruit_label      0
fruit_name       0
fruit_subtype    0
mass             9
width            0
height           9
color_score      0
dtype: int64

In [5]:
print(f'panjang dataset {len(df)} baris')

panjang dataset 60 baris


DATA SPLIT

In [7]:
data = df[['width']]
label = df['height']

data_train, data_test, label_train, label_test = train_test_split(data, label, test_size=.3)

In [8]:
print(f'panjang data training {len(data_train)}',
     f'panjang label training {len(label_train)}',
     f'panjang data testing {len(data_test)}',
     f'panjang label testing {len(label_test)}',
     sep='\n')

panjang data training 42
panjang label training 42
panjang data testing 18
panjang label testing 18


DATA TRANSFORMASI

In [9]:
dataset_normalisasi = df.copy()
dataset_standarirasi = df.copy()

NORMALISASI

In [10]:
scaler = MinMaxScaler()

normalize_dataset = scaler.fit_transform(dataset_normalisasi[['width', 'height']])

normalize_dataset = pd.DataFrame(normalize_dataset)
normalize_dataset.rename(columns={ 0 :'width', 1 : 'height'}, inplace=True)

normalize_dataset.head(5)

width    height
0  0.684211  0.507692
1  0.578947  0.430769
2  0.421053  0.492308
3  0.105263  0.107692
4  0.052632  0.092308

STANDARISASI

In [11]:
dataset_standarirasi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fruit_label    60 non-null     int64  
 1   fruit_name     60 non-null     object 
 2   fruit_subtype  60 non-null     object 
 3   mass           51 non-null     float64
 4   width          60 non-null     float64
 5   height         51 non-null     float64
 6   color_score    60 non-null     float64
dtypes: float64(4), int64(1), object(2)
memory usage: 3.4+ KB


In [22]:
dataset_standarirasi.drop('fruit_name', axis = 1, inplace= True)
dataset_standarirasi.drop('fruit_subtype', axis = 1, inplace= True)
dataset_standarirasi.info()

KeyError: "['fruit_name'] not found in axis"

In [23]:
standart_std = StandardScaler()

scaled_data = standart_std.fit_transform(dataset_standarirasi)

print('Dataset sebelum scalling:',  # SEBELUM
      f'Nilai standar deviasi:\n{np.std(dataset_standarirasi)}',
      sep='\n', end='\n\n')

print('Dataset setelah scalling:',  # SESUDAH
      scaled_data[:6],
      f'Nilai standar deviasi: {np.std(scaled_data)}',
      sep='\n')

Dataset sebelum scalling:
Nilai standar deviasi:
fruit_label       1.129774
mass           4136.846265
width             0.822900
height            1.438906
color_score       0.069964
dtype: float64

Dataset setelah scalling:
[[-1.69650476 -0.1377956   1.64256554 -0.28616516 -2.83240589]
 [-1.69650476 -0.14069636  1.15647956 -0.63365143 -2.26068393]
 [-1.69650476 -0.14166328  0.42735059 -0.35566242 -2.11775343]
 [-0.81137184 -0.16341898 -1.03090735 -2.09309377  0.74085638]
 [-0.81137184 -0.16390244 -1.27395034 -2.16259102  0.59792589]
 [-0.81137184 -0.16486936 -1.51699333 -2.37108278  0.3120649 ]]
Nilai standar deviasi: nan


DATA CLEANING

In [24]:
dataset_ns = df.copy()

In [25]:
imputer_mean = SimpleImputer(strategy='mean')
imputer_median = SimpleImputer(strategy='median')
imputer_modus = SimpleImputer(strategy='most_frequent')

MODUS

In [26]:
df.isna().sum()

fruit_label      0
fruit_name       0
fruit_subtype    0
mass             9
width            0
height           9
color_score      0
dtype: int64

In [27]:
dfmodus = df.copy()

In [29]:
dfmodus['mass'] = imputer_modus.fit_transform(dfmodus[['color_score']])
dfmodus.isna().sum()

fruit_label      0
fruit_name       0
fruit_subtype    0
mass             0
width            0
height           9
color_score      0
dtype: int64

MEAN

In [31]:
dfmodus['color_score'] = imputer_mean.fit_transform(dfmodus[['color_score']])
dfmodus.isna().sum()

fruit_label      0
fruit_name       0
fruit_subtype    0
mass             0
width            0
height           9
color_score      0
dtype: int64

In [32]:
df2 = pd.read_csv('fruits.csv')
df2.head()
dataset_duplicate = df2.fruits()

dataset_duplicate.duplicated().sum()

AttributeError: 'DataFrame' object has no attribute 'fruits'

In [33]:
dataset_duplicate.drop_duplicates(inplace=True)

dataset_duplicate.duplicated().sum()

NameError: name 'dataset_duplicate' is not defined

ENCODING

In [34]:
dataset_ordinal = df.copy()
dataset_one_hot = df.copy()

In [35]:
df['mass'].unique()

array([  192.,   180.,   176.,    86.,    84.,    80.,    76.,   178.,
         172.,   166.,   154.,   164.,   152.,   156.,  1000.,    nan,
         356.,   362.,   204.,   140.,   160.,   158.,   210.,   190.,
         142.,   150., 30000.,   194.,   200.,   186.,   216.,   196.,
         174.,   132.,   130.,   116.,   118.,   120.])

ORDINAL

In [36]:
encoder_ordinal =OrdinalEncoder()

#encoding 
dataset_ordinal['fruit_label'] = encoder_ordinal.fit_transform(dataset_ordinal[['fruit_label']]).astype('int64')

#lihat
dataset_ordinal.head()

fruit_label fruit_name fruit_subtype   mass  width  height  color_score
0            0      apple  granny_smith  192.0    8.4     7.3         0.55
1            0      apple  granny_smith  180.0    8.0     6.8         0.59
2            0      apple  granny_smith  176.0    7.4     7.2         0.60
3            1   mandarin      mandarin   86.0    6.2     4.7         0.80
4            1   mandarin      mandarin   84.0    6.0     4.6         0.79