Asrina Nur Syahbani
2009106131
KB C2 20

In [1]:

import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt
import tensorflow as tf


shape (5,5) random

In [2]:
random_tensor = tf.random.normal([5,5],mean=2)

random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[3.3384104 , 1.221931  , 2.1035073 , 2.1723769 , 2.772706  ],
       [2.9361506 , 1.1205623 , 0.8979665 , 0.72805583, 3.5150363 ],
       [2.868432  , 0.81996703, 3.0853825 , 1.8157849 , 1.952685  ],
       [2.0883179 , 1.6893274 , 1.977207  , 2.4740167 , 2.9291773 ],
       [2.6120121 , 3.1373436 , 3.0214229 , 2.281504  , 2.264393  ]],
      dtype=float32)>

shape (5,5) list bil prima

In [3]:
prime_tensor=tf.constant ([[2,3,5,7,11],[13,17,19,23,29],[31,37,41,43,47],[53,59,61,67,71],[73,79,83,89,97]],dtype=tf.float32)

print(prime_tensor)

tf.Tensor(
[[ 2.  3.  5.  7. 11.]
 [13. 17. 19. 23. 29.]
 [31. 37. 41. 43. 47.]
 [53. 59. 61. 67. 71.]
 [73. 79. 83. 89. 97.]], shape=(5, 5), dtype=float32)


var random tensor

In [4]:
random_tensor.get_shape()

TensorShape([5, 5])

var prime_tensor

In [5]:
tf.shape(prime_tensor).numpy()

array([5, 5])

penjumlahan

In [6]:
print(tf.add(random_tensor, prime_tensor))

tf.Tensor(
[[ 5.3384104  4.221931   7.103507   9.172377  13.772706 ]
 [15.936151  18.120562  19.897966  23.728056  32.515038 ]
 [33.86843   37.819965  44.08538   44.815784  48.952686 ]
 [55.088318  60.689327  62.977207  69.474014  73.92918  ]
 [75.612015  82.137344  86.02142   91.2815    99.2644   ]], shape=(5, 5), dtype=float32)


pengurangan


In [7]:
print(tf.subtract(random_tensor, prime_tensor))

tf.Tensor(
[[  1.3384104  -1.778069   -2.8964927  -4.8276234  -8.227294 ]
 [-10.063849  -15.879437  -18.102034  -22.271944  -25.484964 ]
 [-28.131569  -36.180035  -37.91462   -41.184216  -45.047314 ]
 [-50.911682  -57.310673  -59.022793  -64.525986  -68.07082  ]
 [-70.387985  -75.862656  -79.97858   -86.7185    -94.7356   ]], shape=(5, 5), dtype=float32)


perkalian

In [8]:
print(tf.multiply(random_tensor, prime_tensor))

tf.Tensor(
[[  6.6768208   3.665793   10.517536   15.206638   30.499767 ]
 [ 38.169956   19.049559   17.061363   16.745285  101.93605  ]
 [ 88.921394   30.33878   126.50068    78.07875    91.77619  ]
 [110.68085    99.67031   120.60963   165.75911   207.97159  ]
 [190.67688   247.85014   250.77809   203.05385   219.64613  ]], shape=(5, 5), dtype=float32)


pembagian

In [9]:
print(tf.divide(random_tensor, prime_tensor))

tf.Tensor(
[[1.6692052  0.40731034 0.42070144 0.31033954 0.2520642 ]
 [0.22585773 0.06591543 0.04726139 0.0316546  0.12120815]
 [0.09253006 0.02216127 0.07525323 0.04222756 0.04154649]
 [0.03940222 0.02863267 0.03241323 0.03692562 0.04125602]
 [0.03578099 0.03971321 0.03640268 0.02563488 0.02334426]], shape=(5, 5), dtype=float32)


perpangkatan

In [10]:
print(tf.pow(random_tensor, prime_tensor))

tf.Tensor(
[[1.1144984e+01 1.8244839e+00 4.1183201e+01 2.2832118e+02 7.4463266e+04]
 [1.2053639e+06 6.9248796e+00 1.2940247e-01 6.7575270e-04 6.7914852e+15]
 [1.5380892e+14 6.4634811e-04 1.1525752e+20 1.3796519e+11 4.5678613e+13]
 [8.8965179e+16 2.7234232e+13 1.1459872e+18 2.2802140e+26 1.3770246e+33]
 [2.7490907e+30           inf           inf 7.6153250e+31 2.6935600e+34]], shape=(5, 5), dtype=float32)


logaritma

In [11]:
print(tf.math.log(random_tensor, prime_tensor))

tf.Tensor(
[[ 1.2054948   0.20043238  0.7436061   0.7758219   1.0198238 ]
 [ 1.0770993   0.11383062 -0.1076225  -0.3173775   1.2570499 ]
 [ 1.0537655  -0.19849114  1.1266756   0.59651786  0.66920537]
 [ 0.7363589   0.52433044  0.6816852   0.905843    1.0747216 ]
 [ 0.9601209   1.1433765   1.1057279   0.8248348   0.81730676]], shape=(5, 5), dtype=float32)


maksimum

In [12]:
maxkolom = tf.argmax(random_tensor, axis=0)
maxbaris = tf.argmax(random_tensor, axis=1)
print("Nilai maximum berdasarkan kolom:",maxkolom.numpy())
print("Nilai maximum berdasarkan baris:",maxbaris.numpy())

Nilai maximum berdasarkan kolom: [0 4 2 3 1]
Nilai maximum berdasarkan baris: [0 4 2 4 1]


minimum

In [13]:
minkolom = tf.argmin(random_tensor, axis=0)
minbaris = tf.argmin(random_tensor, axis=1)
print("Nilai minimum berdasarkan kolom:",minkolom.numpy())
print("Nilai minimum berdasarkan baris:",minbaris.numpy())

Nilai minimum berdasarkan kolom: [3 2 1 1 2]
Nilai minimum berdasarkan baris: [1 3 1 1 4]


concenation

In [14]:
concat_rt = (random_tensor)
concat_pt = (prime_tensor)
print("sizes original data:",concat_rt.shape,concat_pt.shape)
concat_rt = tf.concat([concat_rt,concat_pt],axis=0)
print("size  data yang sudah  concenation:",concat_rt.shape)

sizes original data: (5, 5) (5, 5)
size  data yang sudah  concenation: (10, 5)


random tensor

In [15]:
sorting = tf.sort(random_tensor, direction="DESCENDING")
print('urutan random_tensor  secara descending :')
print(sorting)

urutan random_tensor  secara descending :
tf.Tensor(
[[3.3384104  2.772706   2.1723769  2.1035073  1.221931  ]
 [3.5150363  2.9361506  1.1205623  0.8979665  0.72805583]
 [3.0853825  2.868432   1.952685   1.8157849  0.81996703]
 [2.9291773  2.4740167  2.0883179  1.977207   1.6893274 ]
 [3.1373436  3.0214229  2.6120121  2.281504   2.264393  ]], shape=(5, 5), dtype=float32)


prime_tensor

In [16]:
sorting = tf.sort(prime_tensor, direction="DESCENDING")
print('urutan prime_tensor  secara descending :')
print(sorting)

urutan prime_tensor  secara descending :
tf.Tensor(
[[11.  7.  5.  3.  2.]
 [29. 23. 19. 17. 13.]
 [47. 43. 41. 37. 31.]
 [71. 67. 61. 59. 53.]
 [97. 89. 83. 79. 73.]], shape=(5, 5), dtype=float32)
